/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import {
  X,
  Download,
  FileSpreadsheet,
  FileJson,
  Code2,
  Check,
  Copy,
  FileText,
  Bookmark,
  Layers,
  BookOpen,
  Sparkles,
} from 'lucide-react';
import { DatasetConfig, PointData, TDAResult } from '../types/tda';
import { playSoundFeedback } from '../utils/audioSonification';

interface ExportModalProps {
  isOpen: boolean;
  config: DatasetConfig;
  points: PointData[];
  tdaResult: TDAResult | null;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  config,
  points,
  tdaResult,
  onClose,
}) => {
  const [activeTab, setActiveTab] = useState<'jupyter' | 'python' | 'latex' | 'svg' | 'data' | 'bibtex'>('jupyter');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  if (!isOpen || !tdaResult) return null;

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    playSoundFeedback('click');
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  // Generate Academic LaTeX Table
  const generateLatexTable = () => {
    const sigPairsH1 = tdaResult.pairs.filter(
      (p) => p.dimension === 1 && p.lifetime > tdaResult.maxEpsilon * 0.1
    );
    const sigPairsH2 = tdaResult.pairs.filter(
      (p) => p.dimension === 2 && p.lifetime > tdaResult.maxEpsilon * 0.1
    );

    return `% Academic LaTeX Homology Table for ${config.name}
\\begin{table}[htbp]
\\centering
\\caption{Persistent Homology Invariants for Manifold \\textit{${config.name}} with $|X| = ${points.length}$ points.}
\\label{tab:homology_${config.type}}
\\begin{tabular}{lccccc}
\\hline
\\textbf{Dimension ($k$)} & \\textbf{Rank $\\beta_k$} & \\textbf{Max Lifetime} & \\textbf{Mean $\\mu_{\\text{pers}}$} & \\textbf{Entropy $E(D)$} \\\\
\\hline
$H_0$ (Components) & 1 & ${tdaResult.maxEpsilon.toFixed(4)} & ${(tdaResult.vectorization?.totalPersistence / Math.max(1, tdaResult.pairs.length)).toFixed(4)} & ${tdaResult.vectorization?.entropyH0 ?? 0} bit \\\\
$H_1$ (1-Cycles)   & ${sigPairsH1.length} & ${(sigPairsH1[0]?.lifetime || 0).toFixed(4)} & ${(sigPairsH1.reduce((s, p) => s + p.lifetime, 0) / Math.max(1, sigPairsH1.length)).toFixed(4)} & ${tdaResult.vectorization?.entropyH1 ?? 0} bit \\\\
$H_2$ (2-Cavities) & ${sigPairsH2.length} & ${(sigPairsH2[0]?.lifetime || 0).toFixed(4)} & ${(sigPairsH2.reduce((s, p) => s + p.lifetime, 0) / Math.max(1, sigPairsH2.length)).toFixed(4)} & ${tdaResult.vectorization?.entropyH2 ?? 0} bit \\\\
\\hline
\\textbf{Total Invariants} & \\multicolumn{5}{l}{Euler Characteristic $\\chi = ${tdaResult.bettiCurves[tdaResult.bettiCurves.length - 1]?.euler ?? 1}$, $L_2$-Norm $= ${tdaResult.vectorization?.persLandscapeL2Norm}$, 95\\% Conf Band $= ${tdaResult.bootstrapBand}$} \\\\
\\hline
\\end{tabular}
\\end{table}`;
  };

  // Generate Python script using ripser and gudhi
  const pythonScript = `# ==============================================================================
# Topological Data Analysis Pipeline: ${config.name}
# Generated by TDA Studio (Architect: Dhurgham Alsaadi)
# Required dependencies: pip install numpy matplotlib ripser persim gudhi
# ==============================================================================

import numpy as np
import matplotlib.pyplot as plt
from ripser import ripser
from persim import plot_diagrams
import gudhi as gd

# 1. Point Cloud Coordinates (${points.length} sampled points)
points = np.array([
${points.slice(0, 50).map((p) => `    [${p.coords3D.map((c) => c.toFixed(4)).join(', ')}]`).join(',\n')}
    # ... (${Math.max(0, points.length - 50)} remaining coordinates)
])

# 2. Compute Persistent Homology (Vietoris-Rips Filtration)
max_epsilon = ${tdaResult.maxEpsilon.toFixed(4)}
max_dimension = ${config.maxDimension}

print(f"Computing Vietoris-Rips Persistent Homology up to dim {max_dimension}...")
result = ripser(points, maxdim=max_dimension, thresh=max_epsilon, metric='${config.metric}')
diagrams = result['dgms']

# 3. Print Topological Summaries
for dim, dgm in enumerate(diagrams):
    finite_bars = dgm[np.isfinite(dgm[:, 1])]
    lifetimes = finite_bars[:, 1] - finite_bars[:, 0]
    total_pers = np.sum(lifetimes) if len(lifetimes) > 0 else 0
    print(f"Homology H_{dim}: {len(dgm)} features, Total Persistence = {total_pers:.4f}")

# 4. Plot Persistence Diagram with 95% Confidence Band
fig, ax = plt.subplots(1, 2, figsize=(14, 6))

plot_diagrams(diagrams, ax=ax[0], show=False)
confidence_band = ${tdaResult.bootstrapBand}
x_vals = np.linspace(0, max_epsilon, 100)
ax[0].fill_between(x_vals, x_vals, x_vals + confidence_band, color='gray', alpha=0.2, label=f'95% Conf Band (2c={confidence_band})')
ax[0].set_title(f"Persistence Diagram: ${config.name}$")
ax[0].legend()
ax[0].grid(True, linestyle='--', alpha=0.5)

# 5. 3D Point Cloud Scatter
ax[1] = fig.add_subplot(122, projection='3d')
ax[1].scatter(points[:, 0], points[:, 1], points[:, 2], c=points[:, 2], cmap='viridis', s=20, alpha=0.8)
ax[1].set_title(f"Point Cloud ($N={points.length}$)")

plt.tight_layout()
plt.show()
`;

  // Download Jupyter Notebook (.ipynb) JSON
  const downloadJupyterNotebook = () => {
    playSoundFeedback('export');
    const notebookData = {
      cells: [
        {
          cell_type: 'markdown',
          metadata: {},
          source: [
            `# Topological Data Analysis: ${config.name}\n`,
            `*Generated by **TDA Studio** (Architect: Dhurgham Alsaadi)*\n\n`,
            `This notebook executes Persistent Homology computation, Persistence Diagrams, 95% Bootstrap Confidence Bands, and Betti Curves for the **${config.name}** point cloud.`,
          ],
        },
        {
          cell_type: 'code',
          execution_count: null,
          metadata: {},
          outputs: [],
          source: [
            `# Install dependencies if running on Google Colab\n`,
            `!pip install --quiet numpy matplotlib ripser persim gudhi\n`,
          ],
        },
        {
          cell_type: 'code',
          execution_count: null,
          metadata: {},
          outputs: [],
          source: pythonScript.split('\n').map((line) => line + '\n'),
        },
      ],
      metadata: {
        language_info: { name: 'python' },
      },
      nbformat: 4,
      nbformat_minor: 2,
    };

    const blob = new Blob([JSON.stringify(notebookData, null, 2)], {
      type: 'application/x-ipynb+json',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `tda_notebook_${config.type}.ipynb`;
    link.click();
  };

  // Download Vector Graphics SVG
  const downloadDiagramSVG = () => {
    playSoundFeedback('export');
    const svgEl = document.getElementById('persistence-diagram-svg');
    if (!svgEl) return;
    const serializer = new XMLSerializer();
    const source = serializer.serializeToString(svgEl);
    const blob = new Blob([source], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `persistence_diagram_${config.type}.svg`;
    link.click();
  };

  const downloadCSV = () => {
    playSoundFeedback('export');
    const header = 'dimension,birth,death,lifetime,is_infinite\n';
    const rows = tdaResult.pairs
      .map(
        (p) =>
          `${p.dimension},${p.birth.toFixed(6)},${
            p.isInfinite ? 'infinity' : p.death.toFixed(6)
          },${p.lifetime.toFixed(6)},${p.isInfinite}`
      )
      .join('\n');

    const blob = new Blob([header + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `tda_persistence_diagram_${config.type}.csv`;
    link.click();
  };

  const downloadJSON = () => {
    playSoundFeedback('export');
    const exportData = {
      dataset: config.name,
      creator: 'Dhurgham Alsaadi',
      filtrationModel: config.filtrationModel || 'vietoris_rips',
      numPoints: points.length,
      noise: config.noise,
      metric: config.metric,
      bootstrapConfidenceBand: tdaResult.bootstrapBand,
      computationTimeMs: tdaResult.computationTimeMs,
      vectorization: tdaResult.vectorization,
      persistencePairs: tdaResult.pairs,
      phaseTransitions: tdaResult.phaseTransitions,
      bettiCurves: tdaResult.bettiCurves,
      landscapes: tdaResult.landscapes,
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `tda_results_${config.type}.json`;
    link.click();
  };

  const bibtexCitations = `@article{edelsbrunner2008persistent,
  title={Persistent homology: a survey},
  author={Edelsbrunner, Herbert and Harer, John},
  journal={Discrete and Computational Geometry},
  volume={453},
  pages={257--282},
  year={2008}
}

@article{carlsson2009topology,
  title={Topology and data},
  author={Carlsson, Gunnar},
  journal={Bulletin of the American Mathematical Society},
  volume={46},
  number={2},
  pages={255--308},
  year={2009}
}

@article{fasy2014confidence,
  title={Confidence sets for persistence diagrams},
  author={Fasy, Brittany Terese and Lecci, Fabrizio and Rinaldo, Alessandro and Wasserman, Larry and Balakrishnan, Sivaraman and Singh, Aarti},
  journal={The Annals of Statistics},
  volume={42},
  number={6},
  pages={2301--2339},
  year={2014}
}`;

  return (
    <div
      id="export-modal-backdrop"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-150"
    >
      <div
        id="export-modal-card"
        className="bg-[#121215] border border-[#27272a] rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden font-sans text-zinc-200"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#27272a] bg-[#09090b]">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-cyan-950/80 border border-cyan-800/80 text-cyan-400">
              <Download className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-zinc-100 tracking-wide font-mono uppercase flex items-center gap-2">
                <span>Scientific Export & Reproducible Code</span>
                <span className="text-[10px] bg-cyan-950 text-cyan-300 border border-cyan-800 px-2 py-0.5 rounded-full font-normal">
                  Jupyter • Python • LaTeX • SVG
                </span>
              </h2>
              <p className="text-xs text-zinc-400">
                Export one-click runnable Jupyter Notebooks, GUDHI pipelines, LaTeX matrices, and vector figures.
              </p>
            </div>
          </div>
          <button
            id="btn-close-export-modal"
            onClick={() => {
              playSoundFeedback('click');
              onClose();
            }}
            className="p-1.5 text-zinc-400 hover:text-red-400 hover:bg-red-500/20 rounded-lg transition group border border-transparent hover:border-red-500/40"
            title="Close Export Modal"
          >
            <X className="w-5 h-5 group-hover:text-red-400" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex items-center px-6 border-b border-[#27272a] bg-[#09090b] gap-1 overflow-x-auto text-xs font-mono">
          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('jupyter');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'jupyter'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5 text-amber-400" />
            <span>Jupyter (.ipynb)</span>
          </button>

          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('python');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'python'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <Code2 className="w-3.5 h-3.5" />
            <span>Python Script</span>
          </button>

          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('latex');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'latex'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>LaTeX Table</span>
          </button>

          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('svg');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'svg'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Vector SVG</span>
          </button>

          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('data');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'data'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <FileSpreadsheet className="w-3.5 h-3.5" />
            <span>CSV & JSON</span>
          </button>

          <button
            onClick={() => {
              playSoundFeedback('click');
              setActiveTab('bibtex');
            }}
            className={`flex items-center gap-1.5 py-3 px-3.5 border-b-2 transition shrink-0 ${
              activeTab === 'bibtex'
                ? 'border-cyan-500 text-cyan-300 font-bold bg-cyan-950/20'
                : 'border-transparent text-zinc-400 hover:text-zinc-200'
            }`}
          >
            <Bookmark className="w-3.5 h-3.5" />
            <span>BibTeX</span>
          </button>
        </div>

        {/* Tab Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4 text-xs font-mono">
          {activeTab === 'jupyter' && (
            <div className="space-y-4">
              <div className="flex flex-col md:flex-row md:items-center justify-between p-4 bg-zinc-900/80 rounded-xl border border-zinc-800 gap-3">
                <div>
                  <div className="font-bold text-white text-sm font-mono flex items-center gap-2">
                    <BookOpen className="w-4 h-4 text-amber-400" />
                    <span>Run in Google Colab / JupyterLab</span>
                  </div>
                  <p className="text-zinc-400 font-sans text-xs mt-1">
                    Pre-configured .ipynb notebook containing dataset generation, Ripser persistence solver, and publication-ready plots.
                  </p>
                </div>
                <button
                  onClick={downloadJupyterNotebook}
                  className="px-5 py-2.5 bg-gradient-to-r from-amber-600 to-amber-500 hover:from-amber-500 hover:to-amber-400 text-white font-bold rounded-xl shadow-lg flex items-center gap-2 font-mono transition shrink-0"
                >
                  <Download className="w-4 h-4" />
                  <span>Download .ipynb Notebook</span>
                </button>
              </div>

              <div className="border border-zinc-800 rounded-xl p-4 bg-[#09090b] space-y-2">
                <div className="text-zinc-400 font-mono text-[11px] flex items-center justify-between">
                  <span>Python / Ripser Reproduction Snippet:</span>
                  <button
                    onClick={() => copyToClipboard(pythonScript, 'python')}
                    className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300"
                  >
                    {copiedKey === 'python' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copiedKey === 'python' ? 'Copied' : 'Copy Code'}</span>
                  </button>
                </div>
                <pre className="p-3 bg-zinc-950 rounded-lg text-zinc-300 overflow-x-auto leading-relaxed max-h-64 border border-zinc-900">
                  {pythonScript}
                </pre>
              </div>
            </div>
          )}

          {activeTab === 'python' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-zinc-400">
                <span>Complete Python script for Ripser, GUDHI, and Scikit-TDA:</span>
                <button
                  onClick={() => copyToClipboard(pythonScript, 'python')}
                  className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300"
                >
                  {copiedKey === 'python' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedKey === 'python' ? 'Copied Script' : 'Copy Python Script'}</span>
                </button>
              </div>
              <pre className="p-3 bg-[#09090b] rounded-lg border border-[#27272a] text-zinc-300 overflow-x-auto leading-relaxed max-h-80">
                {pythonScript}
              </pre>
            </div>
          )}

          {activeTab === 'latex' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-zinc-400">
                <span>Formatted for IEEE / SIAM / JMLR LaTeX publications:</span>
                <button
                  onClick={() => copyToClipboard(generateLatexTable(), 'latex')}
                  className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300"
                >
                  {copiedKey === 'latex' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedKey === 'latex' ? 'Copied LaTeX' : 'Copy LaTeX'}</span>
                </button>
              </div>
              <pre className="p-3 bg-[#09090b] rounded-lg border border-[#27272a] text-zinc-300 overflow-x-auto leading-relaxed max-h-80">
                {generateLatexTable()}
              </pre>
            </div>
          )}

          {activeTab === 'svg' && (
            <div className="space-y-4">
              <p className="text-zinc-300">
                Export lossless vector graphics figures ready for journal inclusion:
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-[#09090b] p-4 rounded-xl border border-[#27272a] space-y-3 flex flex-col justify-between">
                  <div>
                    <h4 className="font-bold text-zinc-200 text-xs">Persistence Diagram (.SVG)</h4>
                    <p className="text-[11px] text-zinc-400 mt-1">
                      Includes coordinate grids, diagonal line, 95% confidence band, and generator points.
                    </p>
                  </div>
                  <button
                    onClick={downloadDiagramSVG}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-cyan-600 hover:bg-cyan-500 text-white rounded-xl font-bold transition shadow-lg shadow-cyan-950"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download SVG Vector</span>
                  </button>
                </div>

                <div className="bg-[#09090b] p-4 rounded-xl border border-[#27272a] space-y-3 flex flex-col justify-between">
                  <div>
                    <h4 className="font-bold text-zinc-200 text-xs">Raw Point Cloud CSV</h4>
                    <p className="text-[11px] text-zinc-400 mt-1">
                      3D spatial coordinates [x, y, z], density, and cluster labels.
                    </p>
                  </div>
                  <button
                    onClick={downloadCSV}
                    className="flex items-center justify-center gap-1.5 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl font-bold border border-zinc-700 transition"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download Points CSV</span>
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'data' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <button
                onClick={downloadCSV}
                className="p-4 bg-[#09090b] hover:bg-zinc-900 border border-[#27272a] rounded-xl text-left transition flex items-center justify-between group"
              >
                <div>
                  <div className="font-bold text-zinc-200 group-hover:text-cyan-400 transition">
                    Persistence Pairs CSV
                  </div>
                  <div className="text-[11px] text-zinc-400 mt-0.5">
                    dimension, birth, death, lifetime, is_infinite
                  </div>
                </div>
                <Download className="w-4 h-4 text-cyan-400" />
              </button>

              <button
                onClick={downloadJSON}
                className="p-4 bg-[#09090b] hover:bg-zinc-900 border border-[#27272a] rounded-xl text-left transition flex items-center justify-between group"
              >
                <div>
                  <div className="font-bold text-zinc-200 group-hover:text-cyan-400 transition">
                    Complete Results JSON (with 128D ML Vector)
                  </div>
                  <div className="text-[11px] text-zinc-400 mt-0.5">
                    Betti curves, landscapes, entropy, phase transitions
                  </div>
                </div>
                <Download className="w-4 h-4 text-cyan-400" />
              </button>
            </div>
          )}

          {activeTab === 'bibtex' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-zinc-400">
                <span>Standard academic bibliography citations for TDA methodology:</span>
                <button
                  onClick={() => copyToClipboard(bibtexCitations, 'bibtex')}
                  className="flex items-center gap-1 text-cyan-400 hover:text-cyan-300"
                >
                  {copiedKey === 'bibtex' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedKey === 'bibtex' ? 'Copied BibTeX' : 'Copy BibTeX'}</span>
                </button>
              </div>
              <pre className="p-3 bg-[#09090b] rounded-lg border border-[#27272a] text-zinc-300 overflow-x-auto leading-relaxed max-h-80">
                {bibtexCitations}
              </pre>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 border-t border-[#27272a] bg-[#09090b] flex items-center justify-between text-xs text-zinc-400 font-mono">
          <span>TDA Scientific Vectorization & Publication Engine</span>
          <button
            onClick={() => {
              playSoundFeedback('click');
              onClose();
            }}
            className="px-4 py-1.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-lg transition font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
